# Generated by Django 2.1.2 on 2018-10-09 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0001_initial'),
        ('scenicspots', '0001_initial'),
        ('diarys', '0002_diary_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercollect',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='spotscomments',
            name='spots',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenicspots.Spots', verbose_name='景区'),
        ),
        migrations.AddField(
            model_name='spotscomments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='diarycomments',
            name='diary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diarys.Diary', verbose_name='游记'),
        ),
        migrations.AddField(
            model_name='diarycomments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='activecomments',
            name='active',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenicspots.Active', verbose_name='活动'),
        ),
        migrations.AddField(
            model_name='activecomments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
