# Generated by Django 2.1.2 on 2018-10-09 16:24

import datetime
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='我的游记', max_length=20, verbose_name='题目')),
                ('content', models.TextField(verbose_name='内容')),
                ('image', models.ImageField(upload_to=users.models.user_directory_path)),
                ('checknum', models.IntegerField(default=0, verbose_name='查看数')),
                ('commentsnum', models.IntegerField(default=0, verbose_name='评论数')),
                ('is_published', models.BooleanField(default=False, verbose_name='是否发表')),
                ('add_times', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '游记信息',
                'verbose_name_plural': '游记信息',
            },
        ),
    ]
