# Generated by Django 2.1.2 on 2018-10-26 13:25

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('diarys', '0002_diary_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='image',
            field=models.ImageField(default='diary/default.jpg', upload_to=users.models.user_directory_path),
        ),
    ]
