# Generated by Django 2.1.2 on 2018-10-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarys', '0003_auto_20181026_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='image',
            field=models.ImageField(default='diary/default.jpg', upload_to='diary/%Y/%m', verbose_name='封面图'),
        ),
    ]
