# Generated by Django 2.1.2 on 2018-10-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarys', '0004_auto_20181026_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='praisenum',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
    ]
