# Generated by Django 2.1.2 on 2018-10-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarys', '0005_diary_praisenum'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='collectnum',
            field=models.IntegerField(default=0, verbose_name='收藏数'),
        ),
    ]
