# Generated by Django 2.1.2 on 2018-11-08 13:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operation', '0005_auto_20181106_0941'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsOrdersMainTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.CharField(max_length=20, verbose_name='订单号')),
                ('order_describe', models.CharField(max_length=30, verbose_name='订单描述')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='订单的资金总额')),
                ('consignee', models.CharField(max_length=30, verbose_name='收货人')),
                ('address', models.CharField(max_length=100, verbose_name='详细地址')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号')),
                ('zip_code', models.CharField(max_length=6, verbose_name='邮政编码')),
                ('order_state', models.CharField(choices=[('wzf', '未支付'), ('yzf', '已支付'), ('ywc', '已完成')], default='wzf', max_length=3, verbose_name='订单状态')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='订单提交时间')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='订单支付时间')),
                ('finish_time', models.DateTimeField(blank=True, null=True, verbose_name='订单完成时间')),
            ],
            options={
                'verbose_name': '商品订单主表',
                'verbose_name_plural': '商品订单主表',
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.CharField(max_length=20, verbose_name='订单号')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.ShoppingCart', verbose_name='购买的商品信息')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='下单用户')),
            ],
            options={
                'verbose_name': '用户购买商品信息',
                'verbose_name_plural': '用户购买商品信息',
            },
        ),
    ]
