# Generated by Django 2.1.2 on 2018-11-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0002_orderitems_good_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsordersmaintable',
            name='order_describe',
            field=models.CharField(max_length=50, verbose_name='订单描述'),
        ),
    ]
