# Generated by Django 2.1.2 on 2018-11-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0003_auto_20181109_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='good_image',
            field=models.ImageField(default='', upload_to='', verbose_name='商品主图'),
        ),
    ]
