# Generated by Django 2.1.2 on 2018-11-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0004_orderitems_good_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='good_id',
            field=models.IntegerField(default=0, verbose_name='商品id'),
        ),
    ]
