# Generated by Django 2.1.2 on 2018-11-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0008_auto_20181114_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsordersmaintable',
            name='order_state',
            field=models.CharField(choices=[('wzf', '未支付'), ('yzf', '已支付'), ('ywc', '已完成')], default='wzf', max_length=3, verbose_name='订单状态'),
        ),
    ]
