# Generated by Django 2.1.2 on 2018-11-19 15:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pay', '0009_auto_20181114_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenicOrdersMainTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenic_name', models.CharField(default='', max_length=30, verbose_name='景区名称/活动名称')),
                ('buy_num', models.IntegerField(default=1, verbose_name='购买数量')),
                ('ticket_price', models.FloatField(default=0, verbose_name='单价')),
                ('scenic_image', models.ImageField(default='', upload_to='', verbose_name='景区主图/活动主图')),
                ('scenic_id', models.IntegerField(default=0, verbose_name='景区id/活动id')),
                ('order_num', models.CharField(max_length=25, verbose_name='订单号')),
                ('cdk', models.CharField(default='', max_length=25, verbose_name='兑换码')),
                ('order_describe', models.CharField(max_length=50, verbose_name='订单描述')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='订单的资金总额')),
                ('consignee', models.CharField(max_length=30, verbose_name='收货人')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号')),
                ('order_state', models.CharField(choices=[('wzf', '未支付'), ('yzf', '已支付'), ('ywc', '已完成')], default='wzf', max_length=3, verbose_name='订单状态')),
                ('classification', models.CharField(choices=[('mp', '门票'), ('hd', '活动')], default='mp', max_length=2, verbose_name='订单类型')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='订单提交时间')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='订单支付时间')),
                ('received_time', models.DateTimeField(blank=True, null=True, verbose_name='确认收货时间')),
                ('finish_time', models.DateTimeField(blank=True, null=True, verbose_name='订单完成时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='下单用户')),
            ],
            options={
                'verbose_name': '旅游订单',
                'verbose_name_plural': '旅游订单',
            },
        ),
        migrations.RemoveField(
            model_name='ticketsordersmaintable',
            name='user',
        ),
        migrations.DeleteModel(
            name='TicketsOrdersMainTable',
        ),
    ]
