# Generated by Django 2.1.2 on 2018-10-18 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181018_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2018, 10, 18, 16, 23, 40, 253184), verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='city',
            field=models.CharField(default='河南/洛阳/老城区', max_length=50, verbose_name='居住城市'),
        ),
    ]
