# Generated by Django 2.1.2 on 2018-10-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20181019_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='city_addr',
            field=models.CharField(default='410302', max_length=6, verbose_name='居住地代码'),
        ),
    ]
