# Generated by Django 2.1.2 on 2018-11-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20181019_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thecontact',
            name='city',
        ),
        migrations.AddField(
            model_name='thecontact',
            name='city_addr',
            field=models.CharField(default='', max_length=50, verbose_name='所在地区'),
        ),
    ]
