# Generated by Django 2.1.2 on 2018-11-20 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20181109_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='index',
        ),
    ]
