# Generated by Django 2.1.2 on 2018-11-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_banner_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.CharField(max_length=200, verbose_name='访问地址'),
        ),
    ]
