# Generated by Django 2.1.2 on 2018-10-09 16:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Active',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('introduce', models.TextField(verbose_name='活动介绍')),
                ('image', models.ImageField(upload_to='active/%Y/%m', verbose_name='缩略图')),
                ('classification', models.CharField(choices=[('natural', '景区'), ('leisure', '休闲')], default='natural', max_length=10, verbose_name='分类')),
                ('phone', models.CharField(max_length=15, verbose_name='咨询电话')),
                ('go_time', models.DateTimeField(verbose_name='出发时间')),
                ('address', models.CharField(max_length=50, verbose_name='集合地点')),
                ('price', models.FloatField(verbose_name='价格')),
                ('now_num', models.IntegerField(default=0, verbose_name='当前报名人数')),
                ('all_num', models.IntegerField(default=0, verbose_name='总人数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '旅游活动',
                'verbose_name_plural': '旅游活动',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('image', models.ImageField(upload_to='spots/banner/%Y/%m', verbose_name='轮播图')),
                ('index', models.IntegerField(default=100, verbose_name='顺序')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
        migrations.CreateModel(
            name='Spots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('content', models.TextField(verbose_name='内容')),
                ('image', models.ImageField(upload_to='spots/thumbnail/%Y/%m', verbose_name='缩略图')),
                ('picture', models.ImageField(upload_to='spots/mainfigure/%Y/%m', verbose_name='主图')),
                ('classification', models.CharField(choices=[('natural', '景区'), ('leisure', '休闲')], default='natural', max_length=10, verbose_name='分类')),
                ('phone', models.CharField(max_length=15, verbose_name='联系电话')),
                ('businessHours', models.CharField(default='全年', max_length=10, verbose_name='开放时间')),
                ('address', models.CharField(max_length=50, verbose_name='地址')),
                ('price', models.FloatField(verbose_name='价格')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '旅游景区',
                'verbose_name_plural': '旅游景区',
            },
        ),
        migrations.AddField(
            model_name='gallery',
            name='spots',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenicspots.Spots', verbose_name='景区'),
        ),
    ]
