# Generated by Django 2.1.2 on 2018-10-15 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenicspots', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spots',
            old_name='add_time',
            new_name='add_times',
        ),
    ]
