# Generated by Django 2.1.2 on 2018-10-16 16:25

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenicspots', '0002_auto_20181015_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='index',
        ),
        migrations.AddField(
            model_name='spots',
            name='x',
            field=models.DecimalField(decimal_places=6, default=112.460033, max_digits=9, verbose_name='经度'),
        ),
        migrations.AddField(
            model_name='spots',
            name='y',
            field=models.DecimalField(decimal_places=6, default=34.624376, max_digits=9, verbose_name='纬度'),
        ),
        migrations.AlterField(
            model_name='spots',
            name='content',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='内容'),
        ),
    ]
