# Generated by Django 2.1.2 on 2018-10-16 16:25

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenicspots', '0002_auto_20181015_1654'),
    ]

    operations = [

        migrations.AlterField(
            model_name='spots',
            name='content',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='内容'),
        ),
    ]
