# Generated by Django 2.1.2 on 2018-10-10 09:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='商品名称')),
                ('price', models.FloatField(verbose_name='单价')),
                ('num', models.IntegerField(verbose_name='数量')),
                ('freight', models.IntegerField(default=0, verbose_name='运费')),
                ('origin', models.CharField(max_length=20, verbose_name='产地')),
                ('pro_type', models.CharField(choices=[('ncp', '农产品'), ('sg', '水果'), ('gyp', '工艺品'), ('fsp', '副食品')], default='ncp', max_length=3, verbose_name='分类')),
                ('buyers', models.IntegerField(default=0, verbose_name='购买人数')),
                ('comments', models.IntegerField(default=0, verbose_name='评论人数')),
                ('details', models.TextField(verbose_name='商品详情')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '商品信息',
                'verbose_name_plural': '商品信息',
            },
        ),
        migrations.CreateModel(
            name='ProPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=None, verbose_name='商品图')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品图片',
                'verbose_name_plural': '商品图片',
            },
        ),
    ]
