# Generated by Django 2.1.2 on 2018-11-01 14:11

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='details',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='商品详情'),
        ),
    ]
