# Generated by Django 2.1.2 on 2018-11-01 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20181101_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='propic',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
    ]
