# Generated by Django 2.1.2 on 2018-11-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_propic_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propic',
            name='image',
            field=models.ImageField(upload_to='product/%Y/%m', verbose_name='商品图'),
        ),
    ]
