# Generated by Django 2.1.2 on 2018-11-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20181101_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mainimg',
            field=models.ImageField(default='', upload_to='product/mainimg/%Y/%m', verbose_name='商品主图'),
        ),
        migrations.AddField(
            model_name='product',
            name='remind',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='提醒'),
        ),
    ]
